import Head from 'next/head'
import Image from 'next/image'
import Carousels from '../src/components/carousel/Carousel'
import Layouts from '../src/components/Layouts/Layouts'
import Products from '../src/components/products/products/Products'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div  >
      <Head>
        <title>Create Next App</title>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous"></link>



        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layouts>
        <Carousels />
        <Products />
      </Layouts>
    </div>
  )
}
